needs release notes:
- any: ['!docs/release.rst']
- all: [
  '.',
  '!pre-commit-config.yaml',
  '!.gitignore',
  '!FUNDING.yml',
  '!.gitattributes',
  '!.flake8',
  '!.deepsource.toml',
  '!.pep8speaks.yml',
  '!.pyup.yml',
  '!.readthedocs.yaml'
  ]
