needs release notes:
- all: ['!docs/release.rst']
  any: [
    'zarr/*',
    'docs/*',
    'notebooks/*',
    'fixture/*',
    'bench/*',
    '.github/workflows/*', 
    'LICENSE.txt',
    'pyproject.toml',
    'requirements_*.txt'
  ]
